### ISSUE TITLE
feature/561-modify-branding

### ISSUE THREAD

**Issue by reyesjl** [reyesjl/firstfivecloud#22]
## description
I want modify a few things on the home page, the about page, and maybe a few other section to accurately represent our brand as well as be a complete page. For example: The about us page only has a title and subtitle at the moment. I will be formatting it adding content. I will also be adding our sections to the homepage for our services, and perhaps I can sort the footer bug out.

## tasks
- [x] modify home page to contain services section
- [ ] modify about page to contain our information
- [ ] modify catalog to show deal of the day on top
- [ ] modify the catalog to show selectable categories
- [ ] add catalog/product [filters] (world rugby shop, caps, canterbury team kits, vintage jerseys, alumni / traditional )
